apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-container
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game-container
  template:
    metadata:
      labels:
        app: game-container
    spec:
      containers:
      - name: game-container
        image: ghcr.io/importthat/congenial-octo-spoon/game-container:latest
        ports:
          - protocol: TCP
            port: 80       # port you want to access externally
            targetPort: 8080  # container port
        type: NodePort     # or LoadBalancer
        volumeMounts:
        - name: agents
          mountPath: /app/agents
      volumes:
      - name: agents
        emptyDir: {}
